name: .NET

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:

  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore ChatClient/ChatClient.csproj
      
    - name: Build (x86)
      run: dotnet build --no-restore --configuration Debug --output ./bin/x86 /p:Platform=x86 ChatClient/ChatClient.csproj
      
    - name: Build (x64)
      run: dotnet build --no-restore --configuration Debug --output ./bin/x64 /p:Platform=x64 ChatClient/ChatClient.csproj
      
    - name: Upload Artifacts (x86)
      uses: actions/upload-artifact@v4
      with:
        name: Debug-x86
        path: ./bin/x86
        retention-days: 7
        
    - name: Upload Artifacts (x64)
      uses: actions/upload-artifact@v4
      with:
        name: Debug-x64
        path: ./bin/x64
        retention-days: 7