name: .NET

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build-x86:
    name: Build x86
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore ChatClient/ChatClient.csproj
      
    - name: Build
      run: dotnet build --no-restore --configuration Debug --output ./bin/x86 -p:Platform=x86 ChatClient/ChatClient.csproj
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Debug-x86
        path: ./bin/x86/ChatClient.exe
        retention-days: 7

  build-x64:
    name: Build x64
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore ChatClient/ChatClient.csproj
      
    - name: Build
      run: dotnet build --no-restore --configuration Debug --output ./bin/x64 -p:Platform=x64 ChatClient/ChatClient.csproj
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Debug-x64
        path: ./bin/x64/ChatClient.exe
        retention-days: 7
